[package]
name = "tonstruct_proc_macro"
description = "proc macro for tonstruct"
license = "MIT"
version = "0.0.1"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.98" }
