name: Release

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: master
          patchAll: true

      - name: Install cargo-release
        run: cargo install cargo-release
      - name: Cargo login
        run: cargo login ${{ secrets.CRATES_IO_TOKEN }}
      - name: Cargo publish
        run: cargo release ${{ steps.semver.outputs.nextStrict }} --execute

      - name: Create Release
        uses: ncipollo/release-action@v1.15.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ steps.semver.outputs.next }}
          tag: ${{ steps.semver.outputs.next }}
          token: ${{ github.token }}
          generateReleaseNotes: true
